### ISSUE TITLE
Error on run.sh (librispeech)

### ISSUE THREAD

**Issue by bagustris** [bagustris/speechain#1]
I hit the following error when running run.sh (librispeech). I tried to both download librispeech manually (using `data_download.sh` with arg --src_path) and directly using the command below, but both gave the same error.

```bash
$ pwd
/home/bagus/github/SpeeChain/datasets/librispeech
$ bash run.sh
raceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/librispeech/meta_generator.py", line 182, in <module>
    LibriSpeechMetaGenerator().main()
  File "/home/bagus/github/SpeeChain/datasets/meta_generator.py", line 95, in main
    meta_dict = self.generate_meta_dict(**args)
  File "/home/bagus/github/SpeeChain/datasets/librispeech/meta_generator.py", line 167, in generate_meta_dict
    _proc_text = en_text_process(_ori_text, txt_format)
  File "/home/bagus/github/SpeeChain/speechain/utilbox/dump_util.py", line 111, in en_text_process
    while input_text.startswith(' ') or is_punc(input_text[0]):
IndexError: string index out of range
Generating data lengths from /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-100/idx2wav
    to /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-100/idx2wav_len
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 77, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 60, in main
    idx2data = [[idx, data] for idx, data in load_idx2data_file(src_file).items()]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in load_idx2data_file
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in <listcomp>
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 117, in load_single_file
    assert os.path.exists(_file_path), f"{_file_path} doesn't exist!"
AssertionError: /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-100/idx2wav doesn't exist!
Generating data lengths from /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-360/idx2wav
    to /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-360/idx2wav_len
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 77, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 60, in main
    idx2data = [[idx, data] for idx, data in load_idx2data_file(src_file).items()]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in load_idx2data_file
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in <listcomp>
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 117, in load_single_file
    assert os.path.exists(_file_path), f"{_file_path} doesn't exist!"
AssertionError: /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-360/idx2wav doesn't exist!
Generating data lengths from /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-other-500/idx2wav
    to /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-other-500/idx2wav_len
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 77, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 60, in main
    idx2data = [[idx, data] for idx, data in load_idx2data_file(src_file).items()]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in load_idx2data_file
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in <listcomp>
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 117, in load_single_file
    assert os.path.exists(_file_path), f"{_file_path} doesn't exist!"
AssertionError: /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-other-500/idx2wav doesn't exist!
Generating data lengths from /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-clean/idx2wav
    to /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-clean/idx2wav_len
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 77, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 60, in main
    idx2data = [[idx, data] for idx, data in load_idx2data_file(src_file).items()]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in load_idx2data_file
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in <listcomp>
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 117, in load_single_file
    assert os.path.exists(_file_path), f"{_file_path} doesn't exist!"
AssertionError: /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-clean/idx2wav doesn't exist!
Generating data lengths from /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-other/idx2wav
    to /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-other/idx2wav_len
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 77, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 60, in main
    idx2data = [[idx, data] for idx, data in load_idx2data_file(src_file).items()]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in load_idx2data_file
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in <listcomp>
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 117, in load_single_file
    assert os.path.exists(_file_path), f"{_file_path} doesn't exist!"
AssertionError: /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-other/idx2wav doesn't exist!
Generating data lengths from /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-clean/idx2wav
    to /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-clean/idx2wav_len
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 77, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 60, in main
    idx2data = [[idx, data] for idx, data in load_idx2data_file(src_file).items()]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in load_idx2data_file
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in <listcomp>
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 117, in load_single_file
    assert os.path.exists(_file_path), f"{_file_path} doesn't exist!"
AssertionError: /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-clean/idx2wav doesn't exist!
Generating data lengths from /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-other/idx2wav
    to /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-other/idx2wav_len
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 77, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/data_len_generator.py", line 60, in main
    idx2data = [[idx, data] for idx, data in load_idx2data_file(src_file).items()]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in load_idx2data_file
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 155, in <listcomp>
    idx2data_dict = [load_single_file(parse_path_args(f_p)) for f_p in file_path]
  File "/home/bagus/github/SpeeChain/speechain/utilbox/data_loading_util.py", line 117, in load_single_file
    assert os.path.exists(_file_path), f"{_file_path} doesn't exist!"
AssertionError: /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-other/idx2wav doesn't exist!
Post-processing the metadata information in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav.
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-100/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-100/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-360/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-360/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-other-500/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-other-500/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-460/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-460/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-960/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-960/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-clean/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-clean/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-other/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-other/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-clean/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-clean/idx2no-punc_text": No such file or directory Error #2
Generating sentencepiece vocabulary by /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-other/idx2no-punc_text......
Traceback (most recent call last):
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 277, in <module>
    main(**vars(args))
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 256, in main
    generate_vocab_sentencepiece(
  File "/home/bagus/github/SpeeChain/datasets/pyscripts/vocab_generator.py", line 166, in generate_vocab_sentencepiece
    spm.SentencePieceTrainer.train(input=idx2text_path, model_prefix='m',
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 982, in _Train
    return SentencePieceTrainer._TrainFromMap(new_kwargs)
  File "/home/bagus/.local/lib/python3.8/site-packages/sentencepiece/__init__.py", line 927, in _TrainFromMap
    return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
OSError: Not found: "/home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-other/idx2no-punc_text": No such file or directory Error #2
```

@heli-qi Could you suggest a fix for this problem?

**Comment by bagustris** [comment]
From the following code, it says I need to generate metadata with arg `--txt_format no-punc`, but I also hit error with generating meta data with that argument.

https://github.com/search?q=repo%3Aheli-qi%2FSpeeChain%20idx2no-punc_text&type=code

```bash
$ python3 meta_generator.py --tgt_path datasets/librispeech/data/wav --txt_format no-punc
Collecting statistic information of subset train-clean-100 in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-100
Collecting statistic information of subset train-clean-360 in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-clean-360
Collecting statistic information of subset train-other-500 in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/train-other-500
Collecting statistic information of subset dev-clean in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-clean
Collecting statistic information of subset dev-other in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/dev-other
Collecting statistic information of subset test-clean in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-clean
Collecting statistic information of subset test-other in /home/bagus/github/SpeeChain/datasets/librispeech/data/wav/test-other
Start to process the additional LM text corpus......
  0%|                                                                                                                              | 0/40418261 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "meta_generator.py", line 182, in <module>
    LibriSpeechMetaGenerator().main()
  File "/home/bagus/github/SpeeChain/datasets/meta_generator.py", line 95, in main
    meta_dict = self.generate_meta_dict(**args)
  File "meta_generator.py", line 167, in generate_meta_dict
    _proc_text = en_text_process(_ori_text, txt_format)
  File "/home/bagus/github/SpeeChain/speechain/utilbox/dump_util.py", line 111, in en_text_process
    while input_text.startswith(' ') or is_punc(input_text[0]):
IndexError: string index out of range
```

**Comment by bagustris** [comment]
Replacing the following lines in metadata_generator.py seems to work.

https://github.com/bagustris/SpeeChain/blob/2cbec8b7db80e7c40ebeb3fbe20f8b2ba8920fee/datasets/librispeech/meta_generator.py#L167-L171

replace with
```
 if _ori_text.strip():  # Add this check
      _proc_text = en_text_process(_ori_text, txt_format)
         if _proc_text != '':
             proc_lm_text.append(f'{index} {_proc_text}\n')
             index += 1
```
